matcher/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from spreadsheets.views import (
        DataSetList,
        DataSetCreate,
        DataSetDetail,
        SpreadsheetList,
        SpreadsheetCreate,
        SpreadsheetDetail,
        )

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^spreadsheets/$', SpreadsheetList.as_view(), name='spreadsheet-list'),
    url(r'^spreadsheets/add/$', SpreadsheetCreate.as_view(), name='spreadsheet-create'),
    url(r'^spreadsheets/(?P<pk>[\d]+)/$', SpreadsheetDetail.as_view(), name='spreadsheet-detail'),
    url(r'^datasets/$', DataSetList.as_view(), name='dataset-list'),
    url(r'^datasets/add/$', DataSetCreate.as_view(), name='dataset-create'),
    url(r'^datasets/(?P<pk>[\d]+)/$', DataSetDetail.as_view(), name='dataset-detail'),
)

spreadsheets/models.py
from __future__ import unicode_literals
import xlrd

from django.db import models
from django.core.urlresolvers import reverse_lazy

from .utils import ExcelSpreadsheet


class DataSet(models.Model):
    '''
    A collection of Spreadsheets.
    '''
    name = models.CharField(max_length=255)

    def __repr__(self):
        return '<DataSet: {name}>'.format(name=self.name)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('dataset-detail', args=[self.pk])


class Spreadsheet(models.Model):
    '''
    Just an uploaded XLSX file.
    '''
    _file = models.FileField(upload_to='documents/%Y/%m/%d/')
    date_created = models.DateTimeField(auto_now_add=True)
    dataset = models.ForeignKey(DataSet, blank=True, null=True)

    def __repr__(self):
        return '<Spreadsheet: {filename}>'.format(filename=self.filename)

    def __unicode__(self):
        return self.filename

    def get_absolute_url(self):
        return reverse_lazy('dataset-detail', args=[self.pk])

    @property
    def filename(self):
        return self._file.name.split('/')[-1]

    @property
    def get_spreadsheet(self):
        spreadsheet = ExcelSpreadsheet(self.name, self._file.read())
        self._file.seek(0)
        return spreadsheet

spreadsheets/forms.py
from django import forms
from .models import Spreadsheet, DataSet

class SpreadsheetForm(forms.ModelForm):
    class Meta:
        model = Spreadsheet
        exclude = ['number_of_rows', 'number_of_columns']

class DataSetForm(forms.ModelForm):
    class Meta:
        model = DataSet

spreadsheets/views.py
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic import ListView
from django.core.urlresolvers import reverse_lazy

from .models import DataSet, Spreadsheet
from .forms import SpreadsheetForm, DataSetForm
from .utils import ExcelSpreadsheet


class SpreadsheetList(ListView):
    model = Spreadsheet

class SpreadsheetDetail(DetailView):
    model = Spreadsheet

    def get_context_data(self, **kwargs):
        context = {}
        spreadsheet = self.object.get_spreadsheet    
        context['header_row'] = spreadsheet.header_row
        context['data_rows'] = spreadsheet.data
        context.update(kwargs)
        return super(SpreadsheetDetail, self).get_context_data(**context)

class SpreadsheetCreate(CreateView):
    form_class = SpreadsheetForm
    model = Spreadsheet
    success_url = reverse_lazy('spreadsheet-list')

class DataSetList(ListView):
    model = DataSet

class DataSetDetail(DetailView):
    model = DataSet

class DataSetCreate(CreateView):
    form_class = DataSetForm
    model = DataSet
    success_url = reverse_lazy('dataset-list')

spreadsheets/templates/spreadsheets/dataset_detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{ dataset.name }}</h1>
<ul>
    {% for spreadsheet in dataset.spreadsheet_set.all %}
    <li>
        <a href="{% url 'spreadsheet-detail' spreadsheet.pk %}">
            {{ spreadsheet.filename }}
        </a>            
    </li>
    {% endfor %}
</ul>
{% endblock %}

spreadsheets/templates/spreadsheets/dataset_list.html
{% extends "base.html" %}
{% block content %}
<h2>Datasets</h2>
<ul>
	{% for dataset in object_list %}
	<li>
		<a href="{% url 'dataset-detail' dataset.pk %}">
			{{ dataset.name }}
		</a>
		<ul>
			{% for spreadsheet in dataset.spreadsheet_set.all %}
			<li>
				<a href="{% url 'spreadsheet-detail' spreadsheet.pk %}">
					{{ spreadsheet.filename }}
				</a>			
			</li>
			{% endfor %}
		</ul>
	</li>
	{% endfor %}
</ul>
{% endblock %}

spreadsheets/templates/spreadsheets/spreadsheet_detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{ spreadsheet.filename }}</h1>
{% if spreadsheet.dataset %}
<p>Data Set: {{ spreadsheet.dataset.name }}</p>
{% endif %}
<table id="spreadsheet_data">
    <thead>
        <tr>
        	{% for value in header_row %}
            <th>{{ value }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
    	{% for row in data_rows %}
        <tr>
        	{% for value in row %}
            <td>{{ value }}</td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

spreadsheets/templates/spreadsheets/spreadsheet_form.html
{% extends "base.html" %}
{% block content %}
<h1>Add a Spreadsheet</h1>

<form action="{% url "spreadsheet-create" %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <ul>
        {{ form.as_p }}
    </ul>
    <input id="save_spreadsheet" type="submit" value="Save" />
</form>

<a href="{% url "spreadsheet-list" %}">back to list</a>
{% endblock %}

spreadsheets/templates/spreadsheets/spreadsheet_list.html
{% extends "base.html" %}
{% block content %}
<h2>Spreadsheets</h2>
<a href="{% url 'spreadsheet-create' %}">upload</a>
<ul>
	{% for spreadsheet in object_list %}
	<li>
		<a href="{% url 'spreadsheet-detail' spreadsheet.pk %}">
			{{ spreadsheet.filename }}
		</a>
	</li>
	{% endfor %}
</ul>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" media="screen">
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
	{% block content %}
	{% endblock content %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="//code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <!-- other scripts -->
    {% block finalscript %}
    {% endblock %}
  </body>
</html>